# Python list is more than a list

In [19]:
L = list(range(10))

In [20]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
type(L)

list

In [22]:
type(L[0])

int

In [23]:
L2 = [str(c) for c in L]
type(L2[0])

str

In [24]:
all(type(e) == int for e in L)

True

## List can be heterogeneous list

In [25]:
L3 = [True, '2', 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [26]:
tuple(L3)

(True, '2', 3.0, 4)

# Creating Arrays from lists

In [27]:
import numpy as np
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [28]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

## Creating Arrays from scratch
Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into Numpy. Here are some examples:

In [29]:
# create a random integer array
np.random.randint(0, 10, (3, 3))

array([[7, 4, 9],
       [3, 4, 3],
       [6, 2, 6]])

In [30]:
# create a 3x3 array of uniform random values
np.random.random((3, 3))

array([[0.71260407, 0.45976569, 0.14100075],
       [0.64979478, 0.09223806, 0.86600735],
       [0.10971129, 0.72367177, 0.10984151]])

In [31]:
# create 3x3 array of normally distributed data
np.random.normal(0, 1, (3,3))

array([[ 0.10947065,  0.94101378, -0.58395343],
       [ 1.03872174, -1.30675417, -0.33937228],
       [ 0.29104097, -0.94378779,  1.25670468]])