# Python list is more than a list

In [1]:
L = list(range(10))

In [2]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
type(L)

list

In [4]:
type(L[0])

int

In [5]:
L2 = [str(c) for c in L]
type(L2[0])

str

## List can be heterogeneous list

In [6]:
L3 = [True, '2', 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [7]:
tuple(L3)

(True, '2', 3.0, 4)

# Creating Arrays from lists

In [8]:
import numpy as np
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [9]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

## Creating Arrays from scratch
Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into Numpy. Here are some examples:

In [12]:
# create a random integer array
np.random.randint(0, 10, (3, 3))

array([[1, 3, 1],
       [8, 1, 8],
       [9, 5, 8]])

In [13]:
# create a 3x3 array of uniform random values
np.random.random((3, 3))

array([[0.76492644, 0.82048885, 0.30356343],
       [0.75915308, 0.99914655, 0.72089663],
       [0.67602242, 0.8887937 , 0.3312195 ]])

In [15]:
# create 3x3 array of normally distributed data
np.random.normal(0, 1, (3,3))

array([[-0.51881553, -0.0062193 , -1.2274876 ],
       [ 0.30222557, -0.9938821 , -0.9578653 ],
       [ 1.58946551, -0.44661387, -2.11279236]])